services:
  - name: movieflix
    type: web
    plan: free
    env: ruby
    buildCommand: bin/render-build.sh
    startCommand: bundle exec rails s
    envVars:
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: postgre-db
          property: connectionString
      - key: CLOUDINARY_URL
        sync: false

databases:
  - name: postgre-db
    plan: free
    ipAllowList: []
